name: kollegieapp
description: "Kollegie app for Mercantec's kolleige i Viborg"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  http: ^1.4.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# Native splash screen konfiguration
flutter_native_splash:
  color: "#007AFF"
  image: assets/logo.png
  android: true
  ios: true
  web: false
  
  # Dark mode konfiguration
  color_dark: "#121212"
  image_dark: assets/logo.png
  
  # Android 12 konfiguration
  android_12:
    image: assets/logo.png
    color: "#007AFF"
    image_dark: assets/logo.png
    color_dark: "#121212"
    icon_background_color: "#007AFF"
    icon_background_color_dark: "#121212"

# App ikon konfiguration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#007AFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21